### ISSUE TITLE
Can't compile on Kwin 5.27

### ISSUE THREAD

**Issue by cquasar** [a-parhom/LightlyShaders#93]
Cloning into '/home/user/LightlyShaders'...
remote: Enumerating objects: 588, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 588 (delta 174), reused 175 (delta 143), pack-reused 370
Receiving objects: 100% (588/588), 11.21 MiB | 14.33 MiB/s, done.
Resolving deltas: 100% (365/365), done.
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5Config: /usr/lib/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.103.0") 
-- Found KF5ConfigWidgets: /usr/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.103.0") 
-- Found KF5CoreAddons: /usr/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.103.0") 
-- Found KF5Crash: /usr/lib/cmake/KF5Crash/KF5CrashConfig.cmake (found version "5.103.0") 
-- Found KF5GlobalAccel: /usr/lib/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (found version "5.103.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21.1") 
-- Found KF5I18n: /usr/lib/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.103.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found KF5KIO: /usr/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.103.0") 
-- Found KF5Service: /usr/lib/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.103.0") 
-- Found KF5Init: /usr/lib/cmake/KF5Init/KF5InitConfig.cmake (found version "5.103.0") 
-- Found KF5Notifications: /usr/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.103.0") 
-- Found KF5WidgetsAddons: /usr/lib/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake (found version "5.103.0") 
-- Found KF5WindowSystem: /usr/lib/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.103.0") 
-- Found KF5GuiAddons: /usr/lib/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.103.0") 
-- Found KF5: success (found suitable version "5.103.0", minimum required is "5.9.0") found components: Config ConfigWidgets CoreAddons Crash GlobalAccel I18n KIO Service Init Notifications Service WidgetsAddons WindowSystem GuiAddons 
-- Found XCB_XCB: /usr/lib/libxcb.so (found version "1.15") 
-- Found XCB_RENDER: /usr/lib/libxcb-render.so (found version "1.15") 
-- Found XCB_SHAPE: /usr/lib/libxcb-shape.so (found version "1.15") 
-- Found XCB_XFIXES: /usr/lib/libxcb-xfixes.so (found version "1.15") 
-- Found XCB_SHM: /usr/lib/libxcb-shm.so (found version "1.15") 
-- Found XCB_ATOM: /usr/lib/libxcb-util.so (found version "0.4.1") 
-- Found XCB_AUX: /usr/lib/libxcb-util.so (found version "0.4.1") 
-- Found XCB_COMPOSITE: /usr/lib/libxcb-composite.so (found version "1.15") 
-- Found XCB_CURSOR: /usr/lib/libxcb-cursor.so (found version "0.1.4") 
-- Found XCB_DAMAGE: /usr/lib/libxcb-damage.so (found version "1.15") 
-- Found XCB_DPMS: /usr/lib/libxcb-dpms.so (found version "1.15") 
-- Found XCB_DRI2: /usr/lib/libxcb-dri2.so (found version "1.15") 
-- Found XCB_DRI3: /usr/lib/libxcb-dri3.so (found version "1.15") 
-- Found XCB_EVENT: /usr/lib/libxcb-util.so (found version "0.4.1") 
-- Found XCB_EWMH: /usr/lib/libxcb-ewmh.so (found version "0.4.2") 
-- Found XCB_GLX: /usr/lib/libxcb-glx.so (found version "1.15") 
-- Found XCB_ICCCM: /usr/lib/libxcb-icccm.so (found version "0.4.2") 
-- Found XCB_IMAGE: /usr/lib/libxcb-image.so (found version "0.4.1") 
-- Found XCB_KEYSYMS: /usr/lib/libxcb-keysyms.so (found version "0.4.1") 
-- Found XCB_PRESENT: /usr/lib/libxcb-present.so (found version "1.15") 
-- Found XCB_RANDR: /usr/lib/libxcb-randr.so (found version "1.15") 
-- Found XCB_RECORD: /usr/lib/libxcb-record.so (found version "1.15") 
-- Found XCB_RENDERUTIL: /usr/lib/libxcb-render-util.so (found version "0.3.10") 
-- Found XCB_RES: /usr/lib/libxcb-res.so (found version "1.15") 
-- Found XCB_SCREENSAVER: /usr/lib/libxcb-screensaver.so (found version "1.15") 
-- Found XCB_SYNC: /usr/lib/libxcb-sync.so (found version "1.15") 
-- Found XCB_UTIL: /usr/lib/libxcb-util.so (found version "0.4.1") 
-- Found XCB_XF86DRI: /usr/lib/libxcb-xf86dri.so (found version "1.15") 
-- Found XCB_XINERAMA: /usr/lib/libxcb-xinerama.so (found version "1.15") 
-- Found XCB_XINPUT: /usr/lib/libxcb-xinput.so (found version "1.15") 
-- Found XCB_XKB: /usr/lib/libxcb-xkb.so (found version "1.15") 
-- Found XCB_XTEST: /usr/lib/libxcb-xtest.so (found version "1.15") 
-- Found XCB_XV: /usr/lib/libxcb-xv.so (found version "1.15") 
-- Found XCB_XVMC: /usr/lib/libxcb-xvmc.so (found version "1.15") 
-- Found XCB: /usr/lib/libxcb.so;/usr/lib/libxcb-render.so;/usr/lib/libxcb-shape.so;/usr/lib/libxcb-xfixes.so;/usr/lib/libxcb-shm.so;/usr/lib/libxcb-util.so;/usr/lib/libxcb-composite.so;/usr/lib/libxcb-cursor.so;/usr/lib/libxcb-damage.so;/usr/lib/libxcb-dpms.so;/usr/lib/libxcb-dri2.so;/usr/lib/libxcb-dri3.so;/usr/lib/libxcb-ewmh.so;/usr/lib/libxcb-glx.so;/usr/lib/libxcb-icccm.so;/usr/lib/libxcb-image.so;/usr/lib/libxcb-keysyms.so;/usr/lib/libxcb-present.so;/usr/lib/libxcb-randr.so;/usr/lib/libxcb-record.so;/usr/lib/libxcb-render-util.so;/usr/lib/libxcb-res.so;/usr/lib/libxcb-screensaver.so;/usr/lib/libxcb-sync.so;/usr/lib/libxcb-xf86dri.so;/usr/lib/libxcb-xinerama.so;/usr/lib/libxcb-xinput.so;/usr/lib/libxcb-xkb.so;/usr/lib/libxcb-xtest.so;/usr/lib/libxcb-xv.so;/usr/lib/libxcb-xvmc.so (found version "1.15")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/LightlyShaders/qt5build
[  8%] Automatic MOC for target kwin4_effect_lightlyshaders
AutoMoc warning
---------------
"SRC:/lightlyshaders.cpp"
includes the moc file "lightlyshaders.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  8%] Built target kwin4_effect_lightlyshaders_autogen
[ 16%] Building CXX object CMakeFiles/kwin4_effect_lightlyshaders.dir/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp.o
In file included from /home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../lightlyshaders.h:23,
                 from /home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/moc_lightlyshaders.cpp:10,
                 from /home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp:2:
/usr/include/kwineffects.h:3010:20: error: 'std::span' has not been declared
 3010 |     void copy(std::span<GLVertex2D> destination);
      |                    ^~~~
/usr/include/kwineffects.h:3010:24: error: expected ',' or '...' before '<' token
 3010 |     void copy(std::span<GLVertex2D> destination);
      |                        ^
/usr/include/kwineffects.h:3428:10: error: 'optional' in namespace 'std' does not name a template type
 3428 |     std::optional<qreal> renderTargetScale() const;
      |          ^~~~~~~~
/usr/include/kwineffects.h:3428:5: note: 'std::optional' is only available from C++17 onwards
 3428 |     std::optional<qreal> renderTargetScale() const;
      |     ^~~
/home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../lightlyshaders.h:87:21: error: 'GLShader' was not declared in this scope
   87 |     std::unique_ptr<GLShader> m_shader;
      |                     ^~~~~~~~
/home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../lightlyshaders.h:87:29: error: template argument 1 is invalid
   87 |     std::unique_ptr<GLShader> m_shader;
      |                             ^
/home/user/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../lightlyshaders.h:87:29: error: template argument 2 is invalid
make[2]: *** [CMakeFiles/kwin4_effect_lightlyshaders.dir/build.make:76: CMakeFiles/kwin4_effect_lightlyshaders.dir/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:681: CMakeFiles/kwin4_effect_lightlyshaders.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by xNaxdy** [comment]
no problem on my end, compiled straight from master branch

also pls use code formatting

**Comment by cquasar** [comment]
> no problem on my end, compiled straight from master branch
> 
> also pls use code formatting

Tried formatting it but it didn't work, sorry

I managed to compile from master, thanks, has 2.0 been merged to master?

**Comment by a-parhom** [comment]
Master is 2.1 actually. 2.0 doesn't work with Plasma 5.27.
