### ISSUE TITLE
[plasma6] build error! I'm on OpenSUSE tumbleweed.

### ISSUE THREAD

**Issue by anoraktrend** [a-parhom/LightlyShaders#140]
I ran into this error with all dependencies installed.

`return effects->isOpenGLCompositing() && GLFramebuffer::supported();`

**Comment by guiodic** [comment]
Same for me:

[ 83%] Building CXX object src/lightlyshaders/kcm/CMakeFiles/kwin_lightlyshaders_config.dir/lightlyshaders_config.cpp.o
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/lightlyshaders/lightlyshaders.cpp: In static member function ‘static bool KWin::LightlyShadersEffect::supported()’:
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/lightlyshaders/lightlyshaders.cpp:357:61: error: ‘supported’ is not a member of ‘KWin::GLFramebuffer’
  357 |     return effects->isOpenGLCompositing() && GLFramebuffer::supported();
      |                                                             ^~~~~~~~~
[ 85%] Building CXX object src/lightlyshaders/CMakeFiles/kwin_effect_lightlyshaders.dir/kwin_effect_lightlyshaders_autogen/EWIEGA46WW/qrc_lightlyshaders.cpp.o
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp: In static member function ‘static bool KWin::BlurEffect::supported()’:
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp:374:61: error: ‘supported’ is not a member of ‘KWin::GLFramebuffer’
  374 |     return effects->isOpenGLCompositing() && GLFramebuffer::supported() && GLFramebuffer::blitSupported();
      |                                                             ^~~~~~~~~
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp:374:91: error: ‘blitSupported’ is not a member of ‘KWin::GLFramebuffer’
  374 |     return effects->isOpenGLCompositing() && GLFramebuffer::supported() && GLFramebuffer::blitSupported();
      |                                                                                           ^~~~~~~~~~~~~
[ 87%] Building CXX object src/lightlyshaders/kcm/CMakeFiles/kwin_lightlyshaders_config.dir/kwineffects_interface.cpp.o
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp: In member function ‘void KWin::BlurEffect::blur(const KWin::RenderTarget&, const KWin::RenderViewport&, KWin::EffectWindow*, int, const QRegion&, KWin::WindowPaintData&)’:
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp:783:33: error: ‘class KWin::WindowPaintData’ has no member named ‘projectionMatrix’
  783 |         projectionMatrix = data.projectionMatrix();
      |                                 ^~~~~~~~~~~~~~~~
/home/guido/.cache/pacaur/lightlyshaders-plasma6-git/src/LightlyShaders/src/blur/blur.cpp:825:48: error: ‘class KWin::WindowPaintData’ has no member named ‘projectionMatrix’
  825 |             QMatrix4x4 projectionMatrix = data.projectionMatrix();
      |                                                ^~~~~~~~~~~~~~~~
make[2]: *** [src/blur/CMakeFiles/lightlyshaders_blur.dir/build.make:120: src/blur/CMakeFiles/lightlyshaders_blur.dir/blur.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1028: src/blur/CMakeFiles/lightlyshaders_blur.dir/all] Error 2
make[1]: *** Attesa per i processi non terminati....
make[2]: *** [src/lightlyshaders/CMakeFiles/kwin_effect_lightlyshaders.dir/build.make:114: src/lightlyshaders/CMakeFiles/kwin_effect_lightlyshaders.dir/lightlyshaders.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:789: src/lightlyshaders/CMakeFiles/kwin_effect_lightlyshaders.dir/all] Error 2
[ 89%] Linking CXX shared module kwin_lightlyshaders_config.so
[ 91%] Built target kwin_lightlyshaders_config
make: *** [Makefile:146: all] Error 2

**Comment by 0x4c756e61** [comment]
I stumbled on this issue and created a patch file you can apply to fix it, this issue originated because stuff were renamed and moved around in the kwin repo. It works on plasma6.1 beta, I haven't test on 6.0 but I don't see why it wouldn't. 
[lightlyPlasma6.1.txt](https://github.com/user-attachments/files/15525184/lightlyPlasma6.1.txt)

**Comment by guiodic** [comment]
> I stumbled on this issue and created a patch file you can apply to fix it, this issue originated because stuff were renamed and moved around in the kwin repo. It works on plasma6.1 beta, I haven't test on 6.0 but I don't see why it wouldn't. [lightlyPlasma6.1.txt](https://github.com/user-attachments/files/15525184/lightlyPlasma6.1.txt)

it builds but seems doesnt work.

**Comment by 0x4c756e61** [comment]
> > I stumbled on this issue and created a patch file you can apply to fix it, this issue originated because stuff were renamed and moved around in the kwin repo. It works on plasma6.1 beta, I haven't test on 6.0 but I don't see why it wouldn't. [lightlyPlasma6.1.txt](https://github.com/user-attachments/files/15525184/lightlyPlasma6.1.txt)
> 
> it builds but seems doesnt work.

It definitely works on my side, if I forget the fact that Klassy breaks with it, here's a screenshot, I set the corner radius really high to demonstrate it
![image](https://github.com/a-parhom/LightlyShaders/assets/40660493/ebb7423b-0e19-44fd-8dd8-7beb857b3ea8)

**Comment by guiodic** [comment]
I tried again but it doesn't work. I'm on Arch with kde-unstable.

KDE Plasma Version: 6.0.90
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1

**Comment by guiodic** [comment]
ok, ho capito cosa succede. I use egl and O2ES (OpenGL ES) for Kwin. They are much better in terms of fluidity on X11, but some effects like this don't work. It would be nice if it could be ported to O2ES.
