### ISSUE TITLE
Unable to build on kde plasma 5.26.5

### ISSUE THREAD

**Issue by Arpitpandey992** [a-parhom/LightlyShaders#92]
I seem to be getting the following message when building. i'm sort of a noob here, so go easy on me
```
/home/saku/LightlyShaders/qt5build/LightlyShaders/lightlyshaders.cpp:232:5: error: ‘setShader’ was not declared in this scope; did you mean ‘GLShader’?
  232 |     setShader(w, m_shader.get());
      |     ^~~~~~~~~
      |     GLShader
/home/saku/LightlyShaders/qt5build/LightlyShaders/lightlyshaders.cpp: In member function ‘virtual void KWin::LightlyShadersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’:
/home/saku/LightlyShaders/qt5build/LightlyShaders/lightlyshaders.cpp:530:41: warning: ‘void KWindowEffects::enableBlurBehind(WId, bool, const QRegion&)’ is deprecated: Since 5.82. Use enableBlurBehind(QWindow) overload [-Wdeprecated-declarations]
  530 |         KWindowEffects::enableBlurBehind(w->windowId(), true, blur_region);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/KF5/KWindowSystem/KWindowEffects:1,
                 from /home/saku/LightlyShaders/qt5build/LightlyShaders/lightlyshaders.cpp:35:
/usr/include/KF5/KWindowSystem/kwindoweffects.h:162:6: note: declared here
  162 | void enableBlurBehind(WId window, bool enable = true, const QRegion &region = QRegion());
      |      ^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_lightlyshaders.dir/build.make:90: CMakeFiles/kwin4_effect_lightlyshaders.dir/lightlyshaders.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:681: CMakeFiles/kwin4_effect_lightlyshaders.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by a-parhom** [comment]
For Plasma 5.26 use v2.0. Current master branch requires Plasma 5.27, which is mentioned in the README.

**Comment by Arpitpandey992** [comment]
That worked! Thanks a lot!
You sir, are doing god's work here!
